# Generated by Django 5.1.6 on 2025-02-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('job_location', models.CharField(max_length=200)),
                ('vacancy', models.IntegerField()),
                ('wage', models.IntegerField()),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='recruiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiters_username', models.CharField(max_length=200)),
                ('recruiters_password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('recr_phone', models.IntegerField()),
                ('recr_place', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('user_uid', models.IntegerField()),
                ('user_phone', models.IntegerField(max_length=200)),
                ('Date_of_birth', models.DateField()),
            ],
        ),
    ]
