# Generated by Django 5.1.6 on 2025-03-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('user_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='recruiters',
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
