# Generated by Django 5.1.6 on 2025-04-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinder', '0002_user_delete_recruiters_delete_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
