# Generated by Django 5.1.6 on 2025-04-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinder', '0003_remove_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
