# Generated by Django 5.1.6 on 2025-04-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinder', '0004_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='type',
            new_name='category',
        ),
    ]
