# Generated by Django 5.1.6 on 2025-05-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinder', '0007_category_job_datetime_job_description_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='datetime',
        ),
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
