# Generated by Django 5.1.6 on 2025-05-15 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinder', '0008_remove_job_datetime_job_date_job_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobFinder.job'),
        ),
    ]
