# Generated by Django 5.1.6 on 2025-05-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinder', '0009_user_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='jobs',
            new_name='jobs_added',
        ),
    ]
