# Generated by Django 5.1.6 on 2025-05-20 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinder', '0010_rename_jobs_user_jobs_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jobs_added',
        ),
        migrations.AddField(
            model_name='job',
            name='user_recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobFinder.user'),
        ),
    ]
