# Generated by Django 5.1.6 on 2025-06-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinder', '0012_alter_job_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobFinder.user')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobFinder.job')),
            ],
        ),
    ]
