# Generated by Django 5.1.6 on 2025-06-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinder', '0013_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
