# Generated by Django 5.1.6 on 2025-09-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinder', '0014_applications_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='wage',
            field=models.IntegerField(null=True),
        ),
    ]
